name: Unit Tests

on:
  push:
  pull_request:

jobs:
  rspec:
    name: RSpec (${{ matrix.project }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: ["01", "02"]
    defaults:
      run:
        working-directory: ${{ matrix.project }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
          working-directory: ${{ matrix.project }}

      - name: Run RSpec
        run: bundle exec rspec
